[project]
name = "stack_overflow_survey_2024"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    {alias = "P3M", url = "https://packagemanager.posit.co/cran/latest"},
    {alias = "CRAN", url = "https://cloud.r-project.org/"},
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "dplyr",
    "tidyverse",
    { name = "ggchicklet", git = "https://github.com/hrbrmstr/ggchicklet/", commit="64c468dd0900153be1690dbfc5cfb35710da8183"},
    "ggtext",
    "showtext",
    { name = "bbplot", git = "https://github.com/bbc/bbplot/", commit="82af5952230c695bd317d7786587cfffea7f7621"},
    "svglite",
    "palmerpenguins",
    "ggbeeswarm",
    "ggnewscale",
    "ggpubr",
    "survival",
    "survminer",
    "patchwork",
    "pammtools",
    { name = "gghalves", git = "https://github.com/erocoar/gghalves/", commit = "e5c3c79e79f13a00795a2a7774794252d1980d86"},
    { name = "Durga", git = "https://github.com/KhanKawsar/EstimationPlot/", commit = "7b103ff41ad107f3bde8ebe1cc20ee24caeb122a"},
    "dabestr",
    "ggrepel",
    "readr",
    "here",
    "tidytuesdayR",
    "ggExtra",
    "ggdist",
    "farff",
    "shadowtext",
    "ggforce",
    "qatarcars",
    { name = "ggmap", git = "https://github.com/dkahle/ggmap/", commit = "4cdb1fb9b1c2c800f87acbc63dbc5896347f27be"},
    "ggpointdensity",
    "viridis",
    "RColorBrewer",
    { name = "ggh4x", git = "https://github.com/teunbrand/ggh4x/", commit = "63c91b78676eb005ac948fe3498fea5d29013539"},
    "legendry",
    "systemfonts",
    "ragg",
]
